apiVersion: apps/v1
kind: Deployment
metadata:
  name: classedgi-front
  namespace: classedge
spec:
spec:
  replicas: 1
  selector:
    matchLabels:
      app: classedgi-front-pod
  template:
    metadata:
      labels:
        app: classedgi-front-pod
    spec:
      containers:
      - name: classedgi-front-container
        image: jaechang13/classedgifront:20dda3d589b24376d65c509d98b2d36787c5c7b5
        ports:
        - containerPort: 80
