apiVersion: apps/v1
kind: Deployment
metadata:
  name: classedgi-front
  namespace: classedge
spec:
spec:
  replicas: 1
  selector:
    matchLabels:
      app: classedgi-front-pod
  template:
    metadata:
      labels:
        app: classedgi-front-pod
    spec:
      containers:
      - name: classedgi-front-container
        image: jaechang13/classedgifront:70204ba596c977d92f8b8008cc00a5525863697d
        ports:
        - containerPort: 80
